#!/usr/bin/env bash
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# TODO: Make this optional ----------------------------------------------------
echo "Cleaning up previous kubeless deployment."
kubectl delete ns kubeless

while [[ $(kubectl get namespaces | grep kubeless) ]]; do
  echo "Waiting for old namespaces to clear... The following are still active:"
  kubectl get namespaces | grep kubeless
  sleep 5
done

kubectl delete customresourcedefinition functions.k8s.io
kubectl delete clusterrolebinding kubeless-controller-deployer
# -----------------------------------------------------------------------------

echo "Deploying kubeless..."
export RELEASE=v0.3.4
kubectl create ns kubeless

kubectl create -f https://github.com/kubeless/kubeless/releases/download/$RELEASE/kubeless-$RELEASE.yaml

# TODO: Requires gcloud gke permissions?
# kubectl create -f https://github.com/kubeless/kubeless/releases/download/$RELEASE/kubeless-rbac-$RELEASE.yaml

# echo "Kubeless deployed successfully. 🎉"🎉"
