#!/usr/bin/env bash
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

echo "Resetting fission proxies..."

for i in `ps -f | grep 'kubectl -n fission port-forward' | grep -v grep | cut -f4 -d' '`; do
  kill $i
done

CONTROLLER_POD_NAME=$(kubectl -n fission get pod -o name|grep controller|cut -f2 -d'/')
ROUTER_POD_NAME=$(kubectl -n fission get pod -o name|grep router|cut -f2 -d'/')
NATS_POD_NAME=$(kubectl -n fission get pod -o name|grep router|cut -f2 -d'/')
while [[ -z ${CONTROLLER_POD_NAME} ]] || [[ -z ${ROUTER_POD_NAME} ]] || [[ -z ${NATS_POD_NAME} ]]; do
  echo "Waiting for controller and router pods to be ready."
  CONTROLLER_POD_NAME=$(kubectl -n fission get pod -o name|grep controller|cut -f2 -d'/')
  ROUTER_POD_NAME=$(kubectl -n fission get pod -o name|grep router|cut -f2 -d'/')
  NATS_POD_NAME=$(kubectl -n fission get pod -o name|grep nats|cut -f2 -d'/')
  sleep 5
done

echo "Controller pod name: ${CONTROLLER_POD_NAME}"
echo "Router pod name: ${ROUTER_POD_NAME}"

echo "Forwarding controller to localhost:8889"
kubectl -n fission port-forward ${CONTROLLER_POD_NAME} 8881:8888 &

echo "Forwarding fission router to localhost:8887"
kubectl -n fission port-forward ${ROUTER_POD_NAME} 8882:8888 &

echo "Forwarding NATS pod to localhost:4222"
kubectl -n fission port-forward ${NATS_POD_NAME} 4222:4222 &

echo "Finished resetting fission proxies."

if [[ -z ${FISSION_URL} ]] || [[ -z ${FISSION_ROUTER} ]]; then
  echo "Warning one or more of FISSION_URL and FISSION_ROUTER variables unset."
  echo "Please run the following:"
  echo "export FISSION_URL=http://127.0.0.1:8881"
  echo "export FISSION_ROUTER=http://127.0.0.1:8882"
fi
